name: CI
on:
  - pull_request
  - push
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPStan
        run: vendor/bin/phpstan
  phpunit:
    name: "PHPUnit (PHP: ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.3
          - 8.4
        es-version:
          - 8.3.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch ${{ matrix.es-version }}
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.es-version }}
          security-enabled: false
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run PHPUnit
        run: vendor/bin/phpunit
